

////
  __ _ _ __ __ _ _ __ ___  _ __ ___   ___ _ __
 / _` | '__/ _` | '_ ` _ \| '_ ` _ \ / _ | '__|
| (_| | | | (_| | | | | | | | | | | |  __| |
 \__, |_|  \__,_|_| |_| |_|_| |_| |_|\___|_|
 |___/
////
== GRAMMER

.der Buchstabe / -n
f - eff
v - fau
w - wee



=== تحديد ال التعريف
.der
-ant
-ent
-ich
-ling
-ist
-ismus
-or

.das
-chen
-lein
-ment
-um

.die
-anz
-enz
-heit
-keit
-ie
-ei
-ik
-in
-ion
-ität
-schaft
-ung
-ur
-e *معظم*



.صياغة الجمع
-nis**se**
-in**nen** مؤنث
-er معظم المذكر



.Nominativ - الفاعل
der     die     das    die
ein     eine    ein    ---
kein    keine   kein   keine

wer? شخص
was? شيء




=== verbs
auf/räumen تنظيف
vor/bereiten التجهيز
ab/holen إحضار

==== Akkusativ
- haben
- brauchen
- kaufen
- nehmen



> _verb_ immer in *2*
> _subject_ *1 or 3*



mein    meine
dein    deine
sein    seine
ihr     ihr










////
                _
 ___  ___ _ __ | |_ ___ _ __   ___ ___
/ __|/ _ | '_ \| __/ _ | '_ \ / __/ _ \
\__ |  __| | | | ||  __| | | | (_|  __/
|___/\___|_| |_|\__\___|_| |_|\___\___|
////
== Sentence

.أين ولدت؟
Wo sind Sie geboren?      Ich bin in ... geboren.


.أي شيء آخر؟
Was darf es (noch) sein?


.هل يمكنك ...؟
Können Sie das bitte ...?        (erklären/wiederholen/buchstabieren/aufschreiben)
                     *langsam* sprechen?


.روتيني
Ich arbeite __ Stunden *pro* Tag
Ich putze meine Zähne 
Ich gehe *ins Bett*.


.كم الساعة؟
- (um) Wie *spät* ist es? 
- Wie *viel Uhr* ist es?
  Es ist ...
          eins
          halb drei *2:30*
          Viertel vor/nach ...  
          *kurz* vor/nach ...
          ___ Uhr ___ *morgens*



*Wann* fängt ... an?     *Am* Montag  متى
*Wie lange* ...?         2 Stunden

.مع الأسف ما بمشي الحال
Das geht leider nicht


.متى تفتح؟
Wann haben Sie *geschlossen* / *geöffnet* ?

.أريد موعد
- Haben einen Termin am ...?
Ich möchte / hätte gern einen Termin
  *Geht es* ...?
    Nein, ... passt es nicht.


.الشقة بالطابق ال...
In welchem Stock ist die Wohnung?
  Die Wohnung ist im ...

Wie groß ist die Wohnung?

Die Wohnung ist *frei*.








////
                       _
__      _____  _ __ __| |___
\ \ /\ / / _ \| '__/ _` / __|
 \ V  V | (_) | | | (_| \__ \
  \_/\_/ \___/|_|  \__,_|___/
////
== Words

in der Woche     *werktags* خلال الأسبوع
*die Öffnungszeiten أوقات العمل


die Lieblings**mannschaft** الفريق المفضل

.wie oft?
nie         0%
selten      نادراً
manchmal    أحياناً
oft         غالباٌ
meistens    غالباً
immer       100%

2 Mal/einmal      *pro* Tag/Monat



=== البيت
das Dachgeschoss
das Obergeschoss / der Stock
das Erdgeschoss
//-----------------
der Keller

die Monatsmiete إيجار الشهر

der Quadratmeter *m²*

warm -> die Heitzung

der Aufzug مصعد


das Haus / ..er
das Bad / ..er

das Schlafsofa


Januar
Februar
März
April
Mai
Juni
Juli
August
September
Oktober
November
Dezember


=== الأكل
der Vegetarier نباتي

.اجهزة
der Kühlschrank براد
der Herd فرن

.لحمة
das Lammfleisch خروف, غنم
das Rindfleisch بقر
das Schweinefleisch

.طعمه
süß حلو
salzig مالح
sauer حامض
scharf حد



.أعمال
der Übersetzer



=== صفات
laut
ruhig




